### PR TITLE
Added Hebrew for "absolute row number"

### PR DESCRIPTION
**Pull request by dannyba**
Added Hebrew for "absolute row number"

## Author: 
Dan Ben-Avraham

## Language: 
Hebrew

## Terms defined:
absolute row number

## Editor

Assign the PR based on the language to the following person:

| Language   | Person              |
|:----------:|:-------------------:|
| Afrikaans  | @jsteyn, @elletjies |
| Arabic     | @BatoolMM           |
| English    | @zkamvar            |
| French     | @fmichonneau        |
| Portuguese | @beatrizmilz        |
| Spanish    | @ian-flores         |

### CODE REVIEW

**Review by fmichonneau — APPROVED** [review]

**Comment by fmichonneau** [comment]
Thank you Dan! Would you be interested in becoming an editor for Hebrew?

**Comment by dannyba** [comment]
Yes - I would be happy to be the Hebrew editor.
Are there currently open Hebrew request?

Thanks,
Danny

**Comment by baileythegreen** [comment]
Hi @dannyba,

I don't think there are any such requests open (but I'll let someone else confirm). However, I'm working on a part-of-speech feature (pursuant to Issue #60). In order to check that it works, I need to have **something** for it to pull from for the different languages, but for ones I am not familiar with, I can't ensure accuracy of my translations. If you could let me know whether these Google Translate translations of the part-of-speech terms are in line with what would be seen in a Hebrew dictionary, that would save some checking after I submit the PR. Cheers!

```yaml
- language: he
  abbreviation: "נוֹטָרִיקוֹן"
  adjective: "תוֹאַר"
  adverb: "תואר הפועל"
  noun: "שֵׁם עֶצֶם"
  prefix: "קידומת"
  preposition: "מילת יחס"
  pronoun: "כנוי"
  suffix: "סִיוֹמֶת"
  verb: "פועל"
```

**Comment by elletjies** [comment]
@all-contributors please add @dannyba for translation

**Pull request merged**
