### PR TITLE
Change capitalisation in Ukrainian translation of "dictionary"

### PR DESCRIPTION
**Pull request by kashpit0507**
Імменики у глосаріо пишуться з малої букви

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- kashpit

## Language: 

- Ukranian

## Terms defined:

- словник

### CODE REVIEW

**Review by YehorBoiar — APPROVED** [review]

**Comment by YehorBoiar** [comment]
@olexandr-konovalov please merge

**Comment by YehorBoiar** [comment]
@olexandr-konovalov please merge

**Comment by olexandr-konovalov** [comment]
@kashpit0507 @YehorBoiar there are various issues here (4 commits where one will be enough) and it's submitted from the main branch in @kashpit0507's fork (I wonder why)? I will see if I can fix that myself when merging.

**Review by olexandr-konovalov — CHANGES_REQUESTED** [review]
@kashpit0507 is there a chance of you creating a new branch, making a clean edit, and then changing a base branch of this PR to have a clean commit history here (see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request). Also, there are more terms with the similar problem, perhaps consider updating them as well?

**Comment by olexandr-konovalov** [comment]
@kashpit0507 @YehorBoiar sorry, ignore the last comment, that was nonsense - I have realised that it will not work this way. What you need to do is to refactor the main branch in your fork to remove unwanted commits. Oh well, I may try to merge this using "squash & merge" strategy instead, it will have untidy commits in this PR, but just one commit in the `main` branch of the main Glosario repository. Please let me know what do you want to try.

**Comment by olexandr-konovalov** [comment]
@kashpit0507 Also note that the `main` branch of your fork now has commits which are not in the central Glosario repository. That may cause problems in the future. You may want to reset it.

**Comment by olexandr-konovalov** [comment]
@kashpit0507 At the end I've decided that "squash & merge" is easier if you don't have yet working setup on you machine. Next time, ok to continue via web-interface, but please be careful when submitting PRs from/to right branches and repositories. In addition to using the basic GitHub web-interface, you can also use web-based VSCode - see contributing guide, linked from the README at https://github.com/carpentries/glosario

**Comment by elletjies** [comment]
@all-contributors please add @kashpit0507 for translation

**Pull request merged**
