### PR TITLE
issue #115: Adding a definition in Arabic to the existing terms

### PR DESCRIPTION
**Pull request by BatoolMM**
## Terms defined:

- compiler
- argument

## Editor

I only added the Arabic translation of two existing terms which are `compiler` and `argument`. As I said previously, it's a bit tricky to write Arabic characters in YAML file since Arabic is written from right to left, which can easily mess up the indentation. If this one worked fine, I'm happy to add a few terms on daily basis.  

Assign the PR based on the language to the following person:

| Language  | Person        | 
|:---------:|:-------------:|
| Afrikaans | @jsteyn       |
| English   | @zkamvar      |
| Spanish   | @ian-flores   |
| French    | @fmichonneau  |

### CODE REVIEW

**Review by zkamvar — CHANGES_REQUESTED** [review]
Looks good to me. There were some indentation issues to fix, but otherwise, I'm excited to see how it appears on the site.

**Comment by BatoolMM** [comment]
Thank you @zkamvar , I fixed the indentation :)

**Review by zkamvar — APPROVED** [review]

**Comment by zkamvar** [comment]
I'll merge this once #119 is merged and then it should be live. Thank you again, @BatoolMM!

**Comment by BatoolMM** [comment]
Hi @zkamvar , can I submit another PR for other terms defined in Arabic or wait for #121 to merge first?

**Comment by fmichonneau** [comment]
Hi @BatoolMM, please feel free to open a new PR when you are ready. We'll merge this PR and #121 soon. Thank you for your contributions!

**Comment by elletjies** [comment]
@all-contributors please add @BatoolMM for review,translation

**Pull request merged**
