### PR TITLE
add definition for conda and anaconda

### PR DESCRIPTION
**Pull request by talyacooper**
## Author: 

- @talyacooper

## Language: 

- en

## Terms defined:

- conda
- Anaconda

### CODE REVIEW

**Review by jsteyn — COMMENTED** [review]
I think it should also be mentioned that Anaconda is a distribution of Python and R

**Comment by talyacooper** [comment]
@jsteyn I edited the definition -- let me know if you think it's adequate!

**Review by jsteyn — APPROVED** [review]
Thank you @talyacooper. This looks good :-)

**Comment by elletjies** [comment]
@talyacooper Thank you for contributing to Glosario in 2022! We are looking forward to receiving more PRs from you during 2023!

**Comment by elletjies** [comment]
@all-contributors please add @talyacooper for translation

**Pull request merged**
