### PR TITLE
Translate 7 terms (Spanish)

### PR DESCRIPTION
**Pull request by rivaquiroga**
## Author: 

- Riva Quiroga (@rivaquiroga)

## Language: 

- ES

## Terms translated to Spanish:

- anchor
- anti join
- base R
- caching
- CC-0
- character encoding
- folder

### CODE REVIEW

**Review by nicoguaro — COMMENTED** [review]
The check is failing due to an extra empty line in 5782.

Also, I think that the idea is to not change/lint other languages. But maybe somebody can help me here.

**Comment by rivaquiroga** [comment]
I removed the extra empty line. 
If you want, I can revert the typos I fixed in the English definitions.

**Review by nicoguaro — APPROVED** [review]

**Comment by nicoguaro** [comment]
> I removed the extra empty line.
> If you want, I can revert the typos I fixed in the English definitions.

I don't think that you need to take back all those changes. But, keep it in mind. I will ask around, anyway.

**Comment by elletjies** [comment]
@all-contributors please add @rivaquiroga for translation

**Pull request merged**
