### PR TITLE
added the Arabic translation for 4 terms

### PR DESCRIPTION
**Pull request by BatoolMM**
## Author: 

- Batool Almarzouq

## Language: 

- Arabic

## Terms defined:

- Boolean
- catch (an exception)
- NA
- Variable_program

## Editor

Assign the PR based on the language to the following person:

| Language  | Person        | 
|:---------:|:-------------:|
| Afrikaans | @jsteyn       |
| English   | @zkamvar      |
| Spanish   | @ian-flores   |
| French    | @fmichonneau  |

### CODE REVIEW

**Comment by zkamvar** [comment]
@BatoolMM, would you be interested in becoming the official editor for the Arabic language in glosario?

**Comment by BatoolMM** [comment]
@zkamvar, no problem at all. I can be the editor for Arabic entries 👍

**Comment by zkamvar** [comment]
@fmichonneau, could you add @BatoolMM to the glosario-editors team? I don't seem to have the privileges.

**Comment by fmichonneau** [comment]
@zkamvar @BatoolMM is invited and I made you a maintainer of that team so you can add more people in the future.

**Review by zkamvar — APPROVED** [review]

**Pull request merged**
