### PR TITLE
Add definition for 'glossary' (Bangla)

### PR DESCRIPTION
**Pull request by annajiat**
Add bn.md
Add definition for 'glossary' (Bangla)

## Author: 

- Annajiat Alim Rasel

## Language: 

- Bangla

## Terms defined:

- glossary

### CODE REVIEW

**Comment by baileythegreen** [comment]
@zkamvar @fmichonneau We don't have an editor for Bangla, do we?

**Comment by zkamvar** [comment]
Not yet! @annajiat, do you want to be the editor for Bangla?

**Comment by annajiat** [comment]
@zkamvar, yes, I would be glad to have the opportunity to contribute.

**Review by fmichonneau — APPROVED** [review]

**Comment by fmichonneau** [comment]
Thanks! @annajiat you are now part of the @carpentries/glosario-editors-bn team!

**Comment by elletjies** [comment]
@all-contributors please add @annajiat for translation

**Comment by elletjies** [comment]
https://github.com/all-contributors please add @annajiat for documentation

**Comment by elletjies** [comment]
@all-contributors please add @annajiat for translation

**Comment by elletjies** [comment]
@all-contributors please add @annajiat for documentation reviewer questions

**Pull request merged**
