### PR TITLE
Added Japanese translation of repository

### PR DESCRIPTION
**Pull request by naoe-tatara**
## Author: 

- Naoe Tatara

## Language: 

- Japanese

## Terms defined:

- リポジトリ

## Editor

Assign the PR based on the language to the following person:

| Language   | Person                       |
|:----------:|:----------------------------:|
| Japanese   | @tomkellygenetics, @masamiy  |

### CODE REVIEW

**Review by TomKellyGenetics — CHANGES_REQUESTED** [review]
I've added the link for consistency with definitions in other languages. Otherwise looks good to me! Great to have more contributions for Japanese.

よろしくお願いします！

**Comment by naoe-tatara** [comment]
Excellent, thank you, @TomKellyGenetics ! こちらこそ今後ともよろしくお願いいたします。

**Comment by TomKellyGenetics** [comment]
@naoe-tatara I'm okay this but I'll hold off on "approving" so it won't automatically merge as Masami has some feedback.

**Comment by masamiy** [comment]
Hello @naoe-tatara and @TomKellyGenetics, Bear with me - I am still learning how Git works, but will do my share.

**Comment by zkamvar** [comment]
> I'm okay this but I'll hold off on "approving" so it won't automatically merge as Masami has some feedback.

Just popping in to say, for what it's worth, giving reviewer approval does not automatically merge. One of the editors will still need to click the merge button to do that.

Thank you all for you work on this!

**Review by masamiy — APPROVED** [review]
I think it is perfect :) Thanks a lot for your work!

**Comment by elletjies** [comment]
@all-contributors please add @naoe-tatara for translation

**Pull request merged**
