### PR TITLE
Added Hungarian translation

### PR DESCRIPTION
**Pull request by notimre**
## Author: 
- Imre Draskovits
 

## Language: 
- Hungarian

## Terms defined:
- Created Hungarian language as an option

### CODE REVIEW

**Comment by elletjies** [comment]
@notimre do you know of someone who could review this submission?

**Comment by elletjies** [comment]
@notimre, during this issue (https://github.com/carpentries/glosario/issues/556) you indicated that you would try to create the HU page where the definitions will be linked to. Do you still intend of doing this?

**Comment by zkamvar** [comment]
> @notimre ok, we do, however, need the page first then we can add definitions. Once you have created the page PR let me know then I can merge it and then merge the translated definition. Let me know if you need help.

Hi @notimre! There are two more steps to do before we can merge this:

- [ ] create `hu.md` to serve as the language page (see the [instructions for creating the language landing page](https://github.com/carpentries/glosario/blob/main/CONTRIBUTING.md#1-create-the-language-landing-page))
- [ ] add `'hu'` to the `ENTRY_LANGUAGE_KEYS` dict in [`utils/check_glossary.py`](https://github.com/carpentries/glosario/blob/main/utils/check-glossary.py#L33)

Once these two steps are done, then we can merge.

**Review by zkamvar — APPROVED** [review]

**Comment by zkamvar** [comment]
Thank you @notimre!

**Comment by elletjies** [comment]
Thank you @notimre @zkamvar!

**Comment by elletjies** [comment]
@all-contributors please add @imre for translation

**Comment by imre** [comment]
@elletjies thanks for the update!

**Pull request merged**
