### PR TITLE
Updated contribution instructions

### PR DESCRIPTION
**Pull request by elletjies**
Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- 

## Language: 

- 

## Terms defined:

- 
- 
-

### CODE REVIEW

**Comment by zkamvar** [comment]
Thank you for adding this! I'll get it merged. 

FOR SEPTEMBER:

I will want to revisit this later because having instructions in a google doc for this repository somehow indicates that contributing here is difficult. That being said, I know that particular google doc was written in a short amount of time and google doc was chosen for expedience, but at some point, this should be migrated to markdown.

**Review by zkamvar — APPROVED** [review]
LGTM

**Comment by elletjies** [comment]
@zkamvar totally agree - we need to revisit the contribution instructions - I am out until November so can we check-in around then?

**Comment by zkamvar** [comment]
I know there are plugins that can export markdown from GDoc, so I might have a go at it sometime in September.

**Comment by elletjies** [comment]
Thanks! FYI @jsteyn will be my backup while I am out.

**Pull request merged**
