### PR TITLE
Building glossary in multiple languages.

### LINKED ISSUE #18: Home page should list available languages, and each version should be a sub-page
Title says it all: home page should be links to `./en/`, `./es/`, `./fr/`, etc., and the glossaries should be in those pages.

### PR DESCRIPTION
**Pull request by gvwilson**
1.  Put glossary in language-specific file (e.g., ./fr/index.html).
2.  Build glossary in alphabetical order (see _includes/glossary.html).

Closes #18.

### CODE REVIEW

**Comment by zkamvar** [comment]
The structure looks okay, but there is no content in the pages. For example, this is that ./fr/index.html looks like:

```html
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
  <head>
    <title>Glossary</title>
    <link href="/static/site.css" rel="stylesheet" type="text/css">
  </head>
  <body>
    <main>
      <h1>Glossary</h1>

<dl>

</dl>


    </main>
    <footer>
      <p>
        <a href="/">Home</a>
        -
        <a href="/license/">License</a>
        -
        <a href="https://github.com/carpentries/glosario/">GitHub</a>
      </p>
    </footer>
  </body>
</html>
```

I'm afraid that I don't know enough about Liquid or Jekyll to properly debug this :(

**Comment by gvwilson** [comment]
That is strange - when I run `bundle exec jekyll serve` in the `multi-language` branch, I get the following for `_site/fr/index.html`:

```
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
  <head>
    <title>Glossary</title>
    <link href="/static/site.css" rel="stylesheet" type="text/css">
  </head>
  <body>
    <main>
      <h1>Glossary</h1>

<dl>



  <dt id="plus_one">+1</dt>
  <dd>
    Un vote en faveur de quelque chose.


  </dd>


</dl>


    </main>
    <footer>
      <p>
        <a href="/">Home</a>
        -
        <a href="/license/">License</a>
        -
        <a href="https://github.com/carpentries/glosario/">GitHub</a>
      </p>
    </footer>
  </body>
</html>
```

(Only one term is defined in `_data/glossary.yml` for the French version.) Can you please diff `./glossary.yml` and `./_data/glossary.yml` to ensure they're the same, and if not, copy the former to the latter and try a rebuild?

**Comment by zkamvar** [comment]
> (Only one term is defined in `_data/glossary.yml` for the French version.) Can you please diff `./glossary.yml` and `./_data/glossary.yml` to ensure they're the same, and if not, copy the former to the latter and try a rebuild?

That was indeed the issue. There is no `./_data` directory on this branch by default; is it supposed to be created by `bundle exec jekyll serve`? For reference, I am using the github stack for jekyll via [carpentries/lesson-docker](https://github.com/carpentries/lesson-docker). Once I copied glossary.yaml over to ./_data, it worked!

**Comment by gvwilson** [comment]
Yeah, this is going to be a problem... `make serve` copies `./glossary.yml` into `./_data/glossary.yml` and then runs `bundle exec jekyll serve` to build and serve the site, so if you preview using the Makefile, everything is OK (see #17). It feels fragile, but so does symlinking, and moving the glossary definition file into `_data` feels like it'll make things harder for newcomers to find. Thoughts from the crowd?

**Comment by zkamvar** [comment]
does jekyll need the yaml file in the _data directory? Is it not possible to configure it to read from the top level?

**Comment by gvwilson** [comment]
Unfortunately, there are only two places Jekyll can get YAML: from `_config.yml` and from files in the `_data` directory.

**Pull request merged**
