### PR TITLE
Update glossary.yml

### PR DESCRIPTION
**Pull request by eunicenjuguna**
I have added two Swahili definitions

Fill in each of the sections (using NA for those that are not applicable).

## Author: 

- @eunicenjuguna eunicenjuguna

## Language: 

- Kiswhahili

## Terms defined:

- 
- 
-

### CODE REVIEW

**Review by elletjies — APPROVED** [review]

**Comment by elletjies** [comment]
I removed the translation of 'kuunganisha' since this term has already been translated for Kiswahili

**Comment by eunicenjuguna** [comment]
Ohh, sorry for the repetition, I didn't realize. Thank you.

**Comment by elletjies** [comment]
No worries at all :)

**Comment by elletjies** [comment]
@eunicenjuguna Thank you for contributing to Glosario in 2022! We are looking forward to receiving more PRs from you during 2023!

**Comment by elletjies** [comment]
@all-contributors please add @eunicenjuguna for translation

**Pull request merged**
