### PR TITLE
Added DOI definition in Japanese

### PR DESCRIPTION
**Pull request by masamiy**
Added Japanese to 'DOI'.

## Author: 

- @masamiy 

## Language: 

- Japanese

## Terms defined:

- DOI
- 
- 

## Editor

Assign the PR based on the language to the following person:

| Language   | Person                       |
|:----------:|:----------------------------:|
| Afrikaans  | @jsteyn, @elletjies          |
| Arabic     | @BatoolMM                    |
| English    | @baileythegreen, @zkamvar    |
| French     | @fmichonneau                 |
| Japanese   | @tomkellygenetics, @masamiy  |
| Portuguese | @beatrizmilz                 |
| Spanish    | @ian-flores                  |

### CODE REVIEW

**Comment by naoe-tatara** [comment]
Hi, I think this is a perfect translation!! I like that this ends with "のこと"。

**Comment by TomKellyGenetics** [comment]
Excellent! This seems to be ready to merge. So we've agreed to recommend 体言止め style for all future glosario entries in Japanese? @joelnitta agrees with this.

@naoe-tatara we've set up a Japanese Slack channel for glosario here if you wish to participate:
https://carpentries-ja.herokuapp.com/

**Review by TomKellyGenetics — APPROVED** [review]
Accept changes. 🎉

**Comment by masamiy** [comment]
嬉しい！ I assign myself to approve :)

**Comment by TomKellyGenetics** [comment]
@masamiy I think you've made a mistake and closed the PR. This rejects or withdraws the changes rather than "merging" (Green or Purple buttons). I think someone with write-access to the repository needs to approve it.

**Pull request closed without merging**
